Subject/Sunset.WebAPI.Site/Controllers/BookTicketsController.cs
using Sunset.WebAPI.Site.Models.EFModels;
using Sunset.WebAPI.Site.Models.Repositories;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Net.NetworkInformation;
using System.Web;
//using System.Web.Http;
using System.Web.Mvc;
using System.Web.Security;

namespace Sunset.WebAPI.Site.Controllers
{
	public class BookTicketsController : Controller
	{
		// GET: BookTickets
		[Authorize]
		public ActionResult ChoiceMovies()
		{
			return View();
		}
        [Authorize]
        public ActionResult ChoiceDates(int id)
		{
			ViewBag.DateId = id;
			return View();
		}

        [Authorize]
        public ActionResult ChoiceSeats(int movieId, int showdateId, int showtimeId)
		{
			ViewBag.movieId = movieId;
			ViewBag.showdateId = showdateId;
			ViewBag.showtimeId = showtimeId;
			return View();
		}
        [Authorize]
        public ActionResult CheckOrder(int movieScheduleId, string seats)
		{
			ViewBag.movieScheduleId = movieScheduleId;
			ViewBag.seatsId = seats;
			return View();
		}
        [Authorize]
        public ActionResult OrderComplete()
		{
			return View();
		}
	}
}

Subject/Sunset.WebAPI.Site/Controllers/MemberController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace Sunset.WebAPI.Site.Controllers
{
    public class MemberController : Controller
    {
        // GET: Member
        public ActionResult UserHistory()
        {
            return View();
        }
        public ActionResult OrderDetails()
        {
            return View();
        }
        public ActionResult Tickets()
        {
            return View();
        }
        public ActionResult TransactionHistory()
        {
            return View();
        }
    }
}

Subject/Sunset.WebAPI.Site/Views/BookTickets/ChoiceDates.cshtml
@{
    ViewBag.Title = "線上訂票-選擇日期";
}
<head>
    <title>線上訂票-選擇日期</title>
    <link rel="stylesheet" href="~/CSS/styles.css" />
</head>
<style>
    .breadcrumb {
  background-color: #2a2a2a;
  padding: 10px;
  border-radius: 5px;
}

.breadcrumb-item a {
  color: #ffd700;
  text-decoration: none;
}

.breadcrumb-item.active {
  color: #ffffff;
}
</style>
<body>
    <div id="app" class="page-container">
        <div class="login-section container">
            <nav style="--bs-breadcrumb-divider: '>'" aria-label="breadcrumb">
                <ol class="breadcrumb ms-3">
                    <li class="breadcrumb-item"><a href="@Url.Action("index", "Home")">首頁</a></li>
                    <li class="breadcrumb">線上訂票</li>
                    <li class="breadcrumb"><a href="@Url.Action("ChoiceMovies", "BookTickets")">選擇電影</a></li>
                </ol>
            </nav>

            <h2 class="text ms-3">線上訂票步驟</h2>

            <div class="container mt-3 col-12">
                <div class="step-bar">
                    <div class="step-item col-3">1.選擇電影</div>
                    <div class="step-item fw-bolder col-3">2.場次選擇</div>
                    <div class="step-item col-3">3.確認訂單</div>
                    <div class="step-item col-3">4.訂單完成</div>
                </div>

                <div class="row">
                    <div class="col-md-3 col-sm-6">
                        <img class="img-fluid mt-3" :src="imagePath" :alt="movieName" />
                        <p class="text-center fw-bolder mt-2">
                            {{ movieName }}
                        </p>
                    </div>

                    <div class="col-md-9 col-sm-6">
                        <h5 class="fw-bolder mt-3">選擇日期</h5>
                        <p v-if="errorDateMessage" class="text-danger">{{ errorDateMessage }}</p>

                        <div class="d-flex flex-wrap">
                            <div class="date" v-for="day in dates" :key="day.dateId">
                                <button class="btn m-2"
                                        :class="{'btn-primary': selectedDate === day.dateId, 'btn-outline-primary': selectedDate !== day.dateId}"
                                        v-on:click="selectDate(day.dateId)">
                                    {{ day.showtimeDateString }}
                                </button>
                            </div>
                        </div>

                        <div class="col mt-5" v-show="choiceTime && selectedDate">
                            <h5 class="fw-bolder">選擇時間</h5>
                            <p v-if="errorTimeMessage" class="text-danger">{{ errorTimeMessage }}</p>
                            <div class="d-flex flex-wrap">
                                <div class="time" v-for="time in selectedDateTimes" :key="time.timeId">
                                    <button class="btn m-2"
                                            :class="{'btn-primary': selectedTime === time.timeId, 'btn-outline-primary': selectedTime !== time.timeId}"
                                            v-on:click="selectTime(time.timeId)">
                                        {{ time.startTimeMin }}
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="text-end">
                    <a href="#" v-on:click.prevent="handleNextPage" class="btn btn-primary ms-2">
                        下一頁
                    </a>
                </div>
            </div>
        </div>
    </div>

    @section scripts{
        <script>
        const { createApp, ref, onMounted, computed } = Vue;

        const ChoiceDates = {
            setup() {
                const movieName = ref('');
                const mainPicture = ref('');
                const id = @Html.ViewBag.DateId;
                const dates = ref([]);
                const selectedDate = ref(null);
                const selectedTime = ref(null);
                const choiceTime = ref(false);
                const errorDateMessage = ref('');
                const errorTimeMessage = ref('');
                const imagePath = computed(() => {
                    if (mainPicture.value.startsWith('/')) {
                        return mainPicture.value;
                    }
                    return `/images/${mainPicture.value.split('/').pop()}`;
                });
                console.log("selectedDate", selectedDate)
                onMounted(async () => {
                    try {
                        const response = await fetch(`/api/BookTicketsApi/ChoiceDates/${id}`, {
                            method: 'GET',
                            headers: {
                                'Content-Type': 'application/json'
                            }
                        });
                        if (!response.ok) {
                            throw new Error(`HTTP error! status: ${response.status}`);
                        }
                        const data = await response.json();
                        movieName.value = data[0].movieName;
                        mainPicture.value = data[0].mainPicture;
                        dates.value = data;
                    } catch (error) {
                        console.error("Error:", error);
                    }
                });

                const selectedDateTimes = computed(() => {
                    if (!selectedDate.value) return [];
                    const selectedDateObj = dates.value.find(d => d.dateId === selectedDate.value);
                    return selectedDateObj ? selectedDateObj.times : [];
                });

                const selectDate = (dateId) => {
                    selectedDate.value = dateId;
                    choiceTime.value = true;
                    selectedTime.value = null;
                    errorDateMessage.value = "";
                };

                const selectTime = (timeId) => {
                    selectedTime.value = timeId;
                    errorTimeMessage.value = "";
                };


                 const handleNextPage = () => {
                     if (CheckDateAndTime()) {
                         window.location.href = `@Url.Action("ChoiceSeats", "BookTickets")/${id}/${selectedDate.value}/${selectedTime.value}`;
                    }

                };

                const CheckDateAndTime = () => {
                    if (!selectedDate.value) {
                        errorDateMessage.value = "請選擇日期";
                        return false;
                    }
                    if (!selectedTime.value) {
                        errorTimeMessage.value = "請選擇時間";
                        return false;
                    }
                    return true;
                };


                return {
                    imagePath,
                    movieName,
                    mainPicture,
                    dates,
                    selectDate,
                    selectTime,
                    choiceTime,
                    selectedDate,
                    selectedTime,
                    CheckDateAndTime,
                    errorDateMessage,
                    errorTimeMessage,
                    selectedDateTimes,
                    handleNextPage,
                };
            }
        };

        const app = createApp(ChoiceDates);
        app.mount("#app");
        </script>
    }
</body>

Subject/Sunset.WebAPI.Site/Views/BookTickets/ChoiceMovies.cshtml
@{
    ViewBag.Title = "線上訂票-選擇電影";
}
<head>
    <title>線上訂票-選擇電影</title>
    <link rel="stylesheet" href="~/CSS/styles.css" />
    <style>
        .card {
            width: 200px;
            height: auto;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            margin: 10px;
            overflow: visible; /* 確保按鈕顯示 */
            background-color: #fff; /* 白色背景 */
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
            padding: 10px;
        }

            .card img {
                width: 80%;
                height: auto;
                height: 220px; /* 限制圖片高度，確保按鈕有空間 */
                object-fit: cover;
                margin-bottom: 10px;
            }

            .card .text-center {
                margin-top: auto; /* 把按鈕區域推到卡片底部 */
            }

        .btn {
            margin-top: 5px;
        }

    .breadcrumb {
  background-color: #2a2a2a;
  padding: 10px;
  border-radius: 5px;
}

.breadcrumb-item a {
  color: #ffd700;
  text-decoration: none;
}

.breadcrumb-item.active {
  color: #ffffff;
}
    </style>
</head>
<body>
    <div id="app" class="page-container">
        <div class="login-section container">
            <div class="containerbreadcrumb">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb ms-3">
                        <li class="breadcrumb-item"><a href="@Url.Action("index", "Home")">首頁</a></li>
                        <li class="breadcrumb">線上訂票</li>
                        <li class="breadcrumb">選擇電影</li>
                    </ol>
                </nav>
            </div>

            <h2 class="text ms-3">線上訂票步驟</h2>

            <div class="container">
                <div class="step-bar col-12">
                    <div class="step-item fw-bolder col-3">1.選擇電影</div>
                    <div class="step-item col-3">2.場次選擇</div>
                    <div class="step-item col-3">3.確認訂單</div>
                    <div class="step-item col-3">4.訂單完成</div>
                </div>

                <div class="col d-flex flex-wrap mt-4"
                     style="justify-content: space-around">
                    <div class="card border-0 text-center"
                         v-for="c in cards"
                         :key="c.id">
                        <img :src="c.mainPicture" :alt="c.movieName" />
                        <div class="text-center fw-bolder mt-1">{{ c.movieName }}</div>
                        <div class="text-center">
                            <a :href="`@Url.Action("ChoiceDates", "BookTickets")/${c.id}`" class="btn btn-primary">立即購票</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
    
    @section scripts{

        <script>
            const { createApp, ref, onMounted } = Vue;
            const config = {
              
                setup() {
                    const url = "/api/BookTicketsApi/"
                    const cards = ref([]);

                    onMounted(async () => {
                        fetch(url)
                            .then(response => {
                                return response.json();
                            })
                            .then(data => {
                                cards.value = data;
                            })
                            .catch(error => {
                                console.error("Error:", error);
                            });
                    });

                    return { cards };
                },
            };

            const app = createApp(config);
            app.mount("#app");
        </script>
    }
</body>

Subject/Sunset.WebAPI.Site/Views/BookTickets/OrderComplete.cshtml
@{
    ViewBag.Title = "線上訂票-訂單完成";
}
<head>
    <title>線上訂票-訂單完成</title>
</head>
<style>
    .breadcrumb {
  background-color: #2a2a2a;
  padding: 10px;
  border-radius: 5px;
}

.breadcrumb-item a {
  color: #ffd700;
  text-decoration: none;
}

.breadcrumb-item.active {
  color: #ffffff;
}
</style>
<body>
    <div id="app" class="page-container">
        <section class="order-completion mt-5 container">
            <nav style="--bs-breadcrumb-divider: '>'" aria-label="breadcrumb">
                <ol class="breadcrumb ms-3">
                    <li class="breadcrumb-item"><a href="@Url.Action("index", "Home")">首頁</a></li>
                    <li class="breadcrumb">線上訂票</li>
                    <li class="breadcrumb">訂單完成</li>
                </ol>
            </nav>
            <h2 class="text-center">感謝您使用訂票平台</h2>

            <!-- 訂單資訊表格 -->
            <table class="table table-bordered mt-3">
                <tbody>
                    <tr>
                        <th>訂單時間</th>
                        <td>{{orderInfo}}</td>
                    </tr>
                    <tr>
                        <th>訂單編號</th>
                        <td>{{order.orderNumber}}</td>
                    </tr>
                    <tr>
                        <th>電影票號</th>
                        <td>
                            <ul>
                                <!-- 顯示多個電影票號 -->
                                <li v-for="(seat, index) in selectedSeats" :key="index">
                                    {{ seat.ticketNumber }}
                                </li>
                            </ul>
                        </td>
                    </tr>
                    <tr>
                        <th>電影名稱</th>
                        <td>{{ order.movieName }}</td>
                    </tr>
                    <tr>
                        <th>日期場次</th>
                        <td>{{ order.showtimeDateString }} {{ order.startTimeMin }}</td>
                    </tr>
                    <tr>
                        <th>影廳</th>
                        <td>{{ order.auditoriumName }}</td>
                    </tr>
                    <tr>
                        <th>票種</th>
                        <td>
                            <span v-for="(ticket, index) in selectedTickets" :key="index">
                                {{ ticket.name }}:{{ ticket.quantity }}張
                            </span>
                        </td>
                    </tr>
                    <tr>
                        <th>座位</th>
                        <td>
                            <span v-for="(seat, index) in selectedSeats" :key="index">
                                {{ seat.seatNumber }}
                                <span v-if="index < selectedSeats.length - 1">, </span>
                            </span>
                        </td>
                    </tr>
                </tbody>
            </table>

            <div class="text-end mt-3">
                <button v-on:click="goBack" class="btn btn-danger">
                    回到首頁
                </button>
                <button v-on:click="goToNextPage" class="btn btn-primary ms-2">
                    前往票夾
                </button>
            </div>
        </section>
    </div>

    @section scripts{
        <script>
            const { createApp, ref, onMounted, computed } = Vue;

            const config = {

                setup() {
                    const order = ref([]);
                    const selectedTickets = ref([]);
                    const selectedSeats = ref();

                    // 計算總票數
                    const totalTickets = computed(() => {
                        return selectedTickets.value.reduce(
                            (sum, ticket) => sum + ticket.quantity,
                            0
                        );
                    });
                    const getOrder = async () => {
                        const token = getCookie("bookmovie");
                        if (!token) {
                            alert('Token not found. Please log in again.');
                            return;
                        }
                        try {
                            const response = await fetch(`/api/CheckOrderApi/OrderComplete`, {
                                headers: {
                                    'Authorization': `Bearer ${token}`
                                }
                            });
                            if (!response.ok) {
                                throw new Error(`HTTP error! status: ${response.status}`);
                            }
                            const data = await response.json();
                            order.value = data;
                            selectedSeats.value = data.ticketDetails;


                            //return choiceMovieId.value
                        } catch (error) {
                            console.error("Error:", error);
                        }
                    };

                    // 當頁面掛載時，從 localStorage 讀取資料
                    onMounted(() => {
                        getOrder();
                        const savedTickets = JSON.parse(
                            localStorage.getItem("selectedTickets")
                        );

                        if (savedTickets) selectedTickets.value = savedTickets;
                    });

                    const orderInfo = ref(
                        new Date().toLocaleString("zh-TW", {
                            year: "numeric",
                            month: "2-digit",
                            day: "2-digit",
                            hour: "2-digit",
                            minute: "2-digit",
                            second: "2-digit",
                            hour12: false,
                        })
                    );


                    const formattedSeats = computed(() => {
                        return selectedSeats.value.join(", ");
                    });

                    const goBack = () => {
                        window.location.href = "@Url.Action("index", "Home")"; // 回首頁
                    };

                    const goToNextPage = () => {
                        window.location.href = "@Url.Action("Tickets", "Member")"; // 跳轉到票夾
                    };

                    return {
                        order,
                        selectedSeats,
                        orderInfo,
                        goBack,
                        goToNextPage,
                        selectedTickets,
                        formattedSeats,
                        getOrder,

                    };
                },
            };

            const app = createApp(config);
            app.mount("#app");


            function getCookie(name) {
                const value = `; ${document.cookie}`;
                const parts = value.split(`; ${name}=`);
                if (parts.length === 2) return parts.pop().split(';').shift();
            }
        </script>
    }
</body>